[build]
include = ['# 额外包含的文件或目录，如："extra/"']
exclude = [
    ".git",
    ".rmmp",
    "*.tmp",
    "*.log",
]
prebuild = ["echo 'Starting build'"]
build = ["rmm"]
postbuild = ["echo 'Build completed'"]

[build.src]
include = ['# 源代码额外包含的文件，如："docs/"']
exclude = [
    ".git",
    "*.tmp",
    "*.log",
    "node_modules",
]

[build.scripts]
clean = "rm -rf .rmmp/build/* .rmmp/dist/*"
